# This notebook is part of Section 3.2.1 ( NumPy)

## Import NumPy

### We can import NumPy using "import" and we usually use a shortname for our libraries as we will be calling them too many times

In [1]:
import numpy as np

### Create Array using NumPy

In [2]:
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


#### Get the shape of the array : (Very Important)

In [3]:
a.shape

(3,)

### Create Multi-Dimentional Array

In [7]:
a_2d=np.array([[1,2,3],[4,5,6]])
print(a_2d)
print(type(a_2d))
print(a_2d.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


### Perform some numerical operations

In [13]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)
print(np.sqrt(a1))
print(np.mean(a1))
print(np.median(a1))
print(np.max(a1))
print(np.min(a1))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1.         1.41421356 1.73205081]
2.0
2.0
3
1


## NumPy has one of the greatest documentations out there. It will be your friend :)

https://www.numpy.org/devdocs/user/quickstart.html